### ISSUE TITLE
Altering table schema

### ISSUE THREAD

**Issue by eddyod** [ActiveBrainAtlas/Datajoint_Interface#4]
We need lots of fields to be non-required in the database. Currently every field is required and will not accept NULL values. This will probably be a big list but for right now, alter the histology table to allow null values for the virus key. I'm going to do this in the development_database via straight SQL, but we'll need a way to do this via the datajoint interface when creating a schema. See if you can do it right now in the litao_common_atlas_test. The histology table in that database is currently empty.

**Comment by Joeyonng** [comment]
This is done and please check atlas_schema.py
